# How to make mock up Data Frames

* First show the methods for creating DataFrames
* Then show random methods for generating data.

## Imports

In [1]:
import pandas as pd
import numpy as np

## Example 1: single column from a list

In [2]:
input_data = list("xyz")
input_data

['x', 'y', 'z']

In [3]:
df = pd.DataFrame(
    input_data,
)
df

   0
0  x
1  y
2  z

In [4]:
df = pd.DataFrame(
    input_data,
    columns=["letters"]
)
df

  letters
0       x
1       y
2       z

## Example 2: single row from a list

Wrapping list into another list will switch `DataFrame` from being column oriented to being rows oriented.

In [5]:
input_data = list("xyz")
input_data

['x', 'y', 'z']

In [6]:
df = pd.DataFrame(
    [input_data],
)
df

   0  1  2
0  x  y  z

In [7]:
df = pd.DataFrame(
    [input_data],
    columns=["1st", "2nd", "3rd"]
)
df

  1st 2nd 3rd
0   x   y   z

## Example 3: list of lists

List of lists will always be rows oriented - each sublist makes a single row.

In [8]:
input_data = [
    [1, 10, -1],  # Row 1
    [2, 20, -2],  # Row 2
    [3, 30, -3],  # Row 3
    [4, 40, -4],  # Row 4
]


input_data

[[1, 10, -1], [2, 20, -2], [3, 30, -3], [4, 40, -4]]

In [9]:
df = pd.DataFrame(
    data=input_data,
)
df

   0   1  2
0  1  10 -1
1  2  20 -2
2  3  30 -3
3  4  40 -4

In [10]:
df = pd.DataFrame(
    data=input_data,
    columns=["A", "B", "C"]
)
df

   A   B  C
0  1  10 -1
1  2  20 -2
2  3  30 -3
3  4  40 -4

In [11]:
df.T

    0   1   2   3
A   1   2   3   4
B  10  20  30  40
C  -1  -2  -3  -4

In [12]:
df.T.set_axis(list("ABCD"), axis=1).reset_index(drop=True)

    A   B   C   D
0   1   2   3   4
1  10  20  30  40
2  -1  -2  -3  -4

## Example 4 - list of dictionaries

In [13]:
# Very common for API responses
input_data = [
    {"id": 1, "status": "active", "score": 10.5}, # row 1
    {"id": 2, "status": "inactive", "score": 20.1}, # row 2
    {"id": 3, "status": "active", "score": 15.3}, # row 3
    {"id": 4, "status": "active", "score": 7.0}, # row 4
]

In [14]:
df = pd.DataFrame(input_data)
df

   id    status  score
0   1    active   10.5
1   2  inactive   20.1
2   3    active   15.3
3   4    active    7.0

## Example 5 - working with numpy

### 1D array - column oriented

In [15]:

input_data = np.array(list("xyz"))
input_data

array(['x', 'y', 'z'], dtype='<U1')

In [16]:
input_data.shape

(3,)

In [17]:
df = pd.DataFrame(
    data=input_data,
)
df

   0
0  x
1  y
2  z

### 2D: 1 x N - row oriented

In [18]:
# Wrap a list in an extra list like before
input_data = np.array([list("xyz")])
input_data

array([['x', 'y', 'z']], dtype='<U1')

In [19]:
input_data.shape

(1, 3)

In [20]:
df = pd.DataFrame(
    data=input_data,
)
df

   0  1  2
0  x  y  z

### 2D: M X N

In [21]:
input_data = np.array(
    [
        [1, 10, -1],  # Row 1
        [2, 20, -2],  # Row 2
        [3, 30, -3],  # Row 3
        [4, 40, -4],  # Row 4
    ]
)

input_data

array([[ 1, 10, -1],
       [ 2, 20, -2],
       [ 3, 30, -3],
       [ 4, 40, -4]])

In [22]:
df = pd.DataFrame(
    data=input_data,
)
df

   0   1  2
0  1  10 -1
1  2  20 -2
2  3  30 -3
3  4  40 -4

## Example 6: using dict as input

In [23]:
input_data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "City": ["New York", "London", "Paris"],
}

In [24]:
df = pd.DataFrame(input_data)
df

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris

## Example 7 - using `.from_dict()` methods

Summary:
* `column` orientation - `dict` keys become column names
* `index` orientation - `dict` keys become row index

### Column orientation (default)

In [25]:
input_data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "City": ["New York", "London", "Paris"],
}

In [26]:
df = pd.DataFrame.from_dict(
    data=input_data
)
df

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris

### Row orientation

In [27]:
# Existing data makes little sense in a column orientation
df = pd.DataFrame.from_dict(
    data=input_data,
    orient="index",
)
df

             0       1        2
Name     Alice     Bob  Charlie
Age         25      30       35
City  New York  London    Paris

In [28]:
#But timestamped data, e.g. log is better in row orientation
input_data = {
    "2024-01-01 10:00": ["INFO", "User logged in", "Alice"],
    "2024-01-01 10:05": ["WARNING", "Password attempt failed", "Bob"],
    "2024-01-01 10:10": ["ERROR", "Database timeout", "System"],
}

In [29]:
df = pd.DataFrame.from_dict(
    data=input_data,
    orient="index",
    columns=["Level", "Message", "Actor"]
)
df

                    Level                  Message   Actor
2024-01-01 10:00     INFO           User logged in   Alice
2024-01-01 10:05  WARNING  Password attempt failed     Bob
2024-01-01 10:10    ERROR         Database timeout  System

## Example 8: dict of dicts

When each entry in a dictionary is a full entity. E.g. when you pull data from APIs.

In [30]:
input_data = {
    "user_1": {"Name": "Alice", "Age": 25, "City": "New York"},
    "user_2": {"Name": "Bob", "Age": 30, "City": "London"},
    "user_3": {"Name": "Charlie", "Age": 35, "City": "Paris"},
}

In [31]:
# column orientation doesn't work for this data
df = pd.DataFrame.from_dict(
    data=input_data,
)
df

        user_1  user_2   user_3
Name     Alice     Bob  Charlie
Age         25      30       35
City  New York  London    Paris

In [32]:
df = pd.DataFrame.from_dict(
    data=input_data,
    orient="index"
)
df

           Name  Age      City
user_1    Alice   25  New York
user_2      Bob   30    London
user_3  Charlie   35     Paris

In [33]:
# If we want to keep the user ID as a stand alone column, we need to reset the index.
df = (
    pd.DataFrame
    .from_dict(
        data=input_data,
        orient="index"
    )
    .reset_index()
    .rename(columns={"index":"User"})
)

df

     User     Name  Age      City
0  user_1    Alice   25  New York
1  user_2      Bob   30    London
2  user_3  Charlie   35     Paris